all:
	( cd common ; make )
	( cd .common_for_scale ; make )
	( cd letkf ; make )
#	( cd ssio ; make )
	( cd obs ; make )
#	( cd verify ; make )
#	( cd util ; make )
	( cd ensmodel ; make )

clean:
	( cd common ; make clean )
	( cd .common_for_scale ; make clean )
	( cd letkf ; make clean )
#	( cd ssio ; make clean )
	( cd obs ; make clean )
#	( cd verify ; make clean )
#	( cd util ; make clean )
	( cd ensmodel ; make clean )
