all:
	( cd common ; make )
	( cd letkf ; make )
	( cd ssio ; make )
	( cd obs ; make )
	( cd verify ; make )
	( cd util ; make )

clean:
	( cd common ; make clean )
	( cd letkf ; make clean )
	( cd ssio ; make clean )
	( cd obs ; make clean )
	( cd verify ; make clean )
	( cd util ; make clean )
